AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda to analyze monthly Cost and Usage Reports to group costs by program cost center.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Parameters:
  CurBucket:
    Description: >
      The S3 bucket that AWS Billing writes the Cost and Usage Reports to.
    Type: String
    Default: sagebase-cost-reports

Resources:
  CostReportPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LambdaBucketAccess
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${CurBucket}/*"
            Action:
              - "s3:*"

  CostReportFunctionRole:  # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref CostReportPolicy

  CostReportFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: cost_reports/app.lambda_handler
      Runtime: python3.9
      MemorySize: 256
      Role: !GetAtt CostReportFunctionRole.Arn
      Environment:
        Variables:
          CUR_BUCKET: !Ref CurBucket
      Events:  # More info about Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
        ApiTrigger:  # Ad-Hoc runs
          Type: Api
          Properties:
            Path: /run
            Method: get

  S3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: S3EventTrigger
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail:
          eventName:
            - PutObject
            - CopyObject
            - CompleteMultipartUpload
            - RestoreObject
          requestParameters:
            bucketName:
              - !Ref CurBucket
            key:
              - suffix: '.snappy.parquet'
      Targets:
        - Arn: !GetAtt CostReportFunction.Arn
          Id: CostReportFunction

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CostReportApi:
    Description: "API Gateway endpoint URL for Prod stage for Cost Report function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/"
  CostReportFunctionArn:
    Description: "Cost Report Lambda Function ARN"
    Value: !GetAtt CostReportFunction.Arn
  CostReportFunctionRoleArn:
    Description: "Implicit IAM Role created for Cost Report function"
    Value: !GetAtt CostReportFunctionRole.Arn
